env:
  global:
    - PROJECT_NAME=processwire-demo
    # master SHA256-606c78f9bd55e946b34762b7f54b65177eaa37a3fc42559ea62712cf30431b2b
    - secure: "hB/9KoanqxBUKoJwKH8WWbzI7oFbxVhjEA0shWLki346UjnZUQprNNjof7KgA06ADUUfsBuf02DU4dJBGCdU9o/RQm4kFJOz8TgcJzS9n5nTsN2B+0nFc/mJIp1qyMKn4j7p3fylDYAuz8szNKmCwXa6n8by0mtPJ6j7pgNK2f4xzzWB2x3f7wP7sXhhJkwJUXYjii1NC1zR5hwcP0TJl8X9opJRgNGwABU7mTkMNf1QxkYUK3VyyE7clOSYMr4DRB9aq+fjeykeuKuFqIk+vjk3Nb2LaroRcWAU8fDke14M71zYfH0opjGnezb12j3NU58VrESbjL/C5p/3bECfPJsvzmdhwfnVgdZvx1+gWjhHWqnm9YQbmc7+EYuO+T2guXa7dKxcn5oU7O/QiBRG4hKsubFHwFfZNG7hblDwDo4+V0tz+02T7mI6Ka3T6jVLSgt3t+ScfY10HyKKxRLdWldskLwxI47Tm6ZU8gL3Gjzfv2zV6okr/Cv+r5hjxvPTxeXqVicBZ/NqYawSrhnEMyzFWizqfeTjJAjp+AMX6nWK4820ETvwD/s+gzV3cj8ESErM2N+yabWzGkwC/B6gibpjEnKbeSNbs6eQaPUm4d2U0YfGSPf8vJeQ47iwJhohMLYppnVM1omyFohvR06HPiDhtEj5MOviXYMoKs0is7c="
    # beta SHA256-af7507b9411c78ff3df1efd621fbcb9ec9ab7057af1aa1e543dbca6a9c4020f0
    # secure: ""
script:
  - true
notifications:
  email: false
language: node_js
node_js:
  - "6"
before_deploy:
  - 'git config --global user.email "deploy@travis-ci"'
  - 'git config --global user.name "[Deploy]"'
  - export GIT_FTP_URL_BRANCH=GIT_FTP_URL_$TRAVIS_BRANCH
  - './git-ftp add-scope $TRAVIS_BRANCH "${!GIT_FTP_URL_BRANCH}"'
  - git config git-ftp.syncroot public
  - npm install -g uglify-js
  - gem install sass -v 3.4.23 --no-ri --no-rdoc
deploy:
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: beta